### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by kezkankrayon** [benesch/homebrew-pgloader#1]
I'm receiving the following compilation error:

==> make pgloader-standalone
Fatal SIMPLE-ERROR:
  Compilation failed: function called with one argument, but wants exactly zero
See also:
  The ANSI Standard, Section 3.2.2.3 in /private/tmp/pgloader-4YTw6z/pgloader-3.0.98/lib/iterate/iterate.lisp
make: **\* [pgloader-standalone] Error 1

**Comment by benesch** [comment]
This formula is way out of date, sorry! Let me see what I can do.

**Comment by benesch** [comment]
Try now!

**Comment by benesch** [comment]
homebrew/homebrew#37933 should hopefully supersede this repository soon! Closing.

**Comment by kezkankrayon** [comment]
Was able to brew install with homebrew 17fc083b. No longer seems to be an issue. Thank you.

**Comment by benesch** [comment]
Cheers!
