### ISSUE TITLE
How to bump to 3.2.2?

### ISSUE THREAD

**Issue by richardkmichael** [benesch/homebrew-pgloader#2]
Hello,

Pardon me for hijacking issues with just a question. :-)  I realize your formula has been merged to Homebrew, but I thought I'd inquire here because you were responsible for the original formula.

I wanted to trivially PR to bump pgloader to `v3.2.2` (there is a helpful fix for `NULL` datetime values when loading from sqlite).  However it turns out, as I'm new to writing homebrew formulae and know nothing about quicklisp, this is less trivial than I thought. :-)

Using `brew edit pgloader`, I adjusted the main URL and SHA1:

```
class PgLoader < Formula
  # .. snip
  url "https://github.com/dimitri/pgloader/archive/v3.2.2.tar.gz"
  sha256 "5fe5c115e277a9dd616b1077f89bffdf978bc6983ce62d99af9a218142c39e40"
  # .. snip
```

But I noticed the pgloader tarball is also needed via quicklisp as a homebrew `resource` later:

```
resource "pgloader" do
  url "https://beta.quicklisp.org/archive/pgloader/2015-03-02/pgloader-3.2.0.tgz"
  sha256 "b6ee64da37b9c781deafbfb5f698bdd2d005bcb03380b7072e0cf1cecc237204"
end
```

To bump homebrew pgloader, should I submit a request to the quicklisp project to bump their tarball, then update the brew `resource` section with that new quicklisp tarball?

(Aside, I tried leaving the `3.2.0` quicklisp tarball as the resource and installing, but homebrew installed `3.2.0` and did nothing with the `3.2.2` tarball it downloaded during the preparation phase.)

If I'm about to build locally (there is no bottle for 3.2.2, obviously), why do I need the quicklisp built library?  Or, conversely, if homebrew simply uses the quicklisp built library, why do I need to download the tarball from GitHub?

Thanks for your pgloader contribution, it's very helpful.

**Comment by benesch** [comment]
Yikes! That's a bug. I patched up the formula to properly use the initially-downloaded version during the build phase (628d179), and also updated the resource stanzas for the latest Quicklisp distribution (e55f50). Sorry for the confusion!

[See also https://github.com/benesch/quicklisp-homebrew-roundup so you don't have to manually update the resource blocks.]

**Comment by benesch** [comment]
Thanks for reporting this! So glad this turned out to be useful to someone. :)

**Comment by richardkmichael** [comment]
Thank you for the very fast reply.  Today I pulled homebrew and tried to `brew install pgloader`.

Although I do not have pgloader installed at the moment, because I had installed previously, `brew install pgloader` dies with `Error: SHA256 mismatch` on a file it finds in its download cache.  It seems although it should (re-)download the file because the content has changed, it decides to skip (based on name alone?).  This seems like a homebrew core issue; it should compare SHA256 of the cached file with the brew formula SHA256 and re-download if different, regardless of the filename (this would also help any "corrupted during download" problems).  I'm just guessing, however.

```
(localhost) $ brew install pgloader
==> Downloading https://github.com/dimitri/pgloader/archive/v3.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/pgloader-3.2.2.tar.gz
==> Downloading https://beta.quicklisp.org/archive/usocket/2015-06-08/usocket-0.6.3.2.tgz
######################################################################## 100.0%
==> Downloading https://beta.quicklisp.org/archive/md5/2015-08-04/md5-20150804-git.tgz
######################################################################## 100.0%
==> Downloading https://beta.quicklisp.org/archive/ironclad/2014-11-06/ironclad_0.33.0.tgz
Already downloaded: /Library/Caches/Homebrew/pgloader--ironclad-0.33.0.tgz
==> Downloading https://beta.quicklisp.org/archive/command-line-arguments/2015-07-09/command-line-arguments-20150709-git.tgz
Already downloaded: /Library/Caches/Homebrew/pgloader--command-line-arguments-line.tgz
Error: SHA256 mismatch
Expected: b032a2a750fe335be6b7327e8f87d39ed1669c671f010544b838522606a9c17c
Actual: 0a3033de15cbd0a7215186bcc450dec031f28ce4a2d4b490aa23b65c23473470
Archive: /Library/Caches/Homebrew/pgloader--command-line-arguments-line.tgz
To retry an incomplete download, remove the file above.
```

I assumed I'd clean the cache then install, so I checked `brew cleanup -n`, but the `resource` files won't be cleaned up (removed):  (I did run a real `brew cleanup` too.)

```
(localhost) $ brew cleanup -n|grep pgloader
Would remove: /Library/Caches/Homebrew/pgloader-3.2.0.mountain_lion.bottle.tar.gz (20M)
Would remove: /Library/Caches/Homebrew/pgloader-3.2.0.tar.gz (3.7M)
```

Should the formula indicate to homebrew that `resources` (`/Library/Caches/Homebrew/pgloader-*`) are to removed on `brew cleanup`?

Of course, the "quick fix" was just: `rm -f /Library/Caches/Homebrew/pgloader-*`.

Thank you again for the quick update.

**Comment by benesch** [comment]
I noticed that too! It seems the resource cache is too aggressive. Would you mind filing this upstream? Looks like a Homebrew core issue; the formula shouldn't need to do anything special to get its resources picked up by `brew cleanup`.

**Comment by richardkmichael** [comment]
Will do; yes, if there's no special behaviour required by the formula, it's
core.  Thanks for replying!
